node_size: 4
arrow_size: 2
line_width: 0.2
node_alpha_on_3D: 1.0
node_alpha_off_3D: 0.1
line_alpha_3D: 0.05
increment: 5
n_seconds: 10
angle_offset_3D: 15
num_frames: 3
trace_best: 0
trace_gene_origins: 0
interp_factor: 30
interpolation_type: cubic

subgraph_node_size: 100
subgraph_width: 0.3
subgraph_height: 0.3
subgraph_x_spacing: 1
subgraph_y_spacing: 1

epochs: 300
batch_size: 512
verbose: true
learning_rate: 0.0001
hidden_layer1_size: 256
hidden_layer2_size: 128

add_timestamp_to_vis: true
transform_to_01: true
vis_image_type: "pdf"
