
args:
  node_size: 4
  arrow_size: 2
  line_width: 0.2
  node_alpha_on_3D: 1.0
  node_alpha_off_3D: 0.1
  line_alpha_3D: 0.05
  increment: 5
  n_seconds: 10
  angle_offset_3D: 15
  num_frames: 3
  trace_best: 0
  trace_gene_origins: 0
  interp_factor: 30

  subgraph_node_size: 100
  subgraph_width: 0.3
  subgraph_height: 0.3
  subgraph_x_spacing: 1
  subgraph_y_spacing: 1

  epochs: 300
  batch_size: 512
  verbose: true
  learning_rate: 0.0001

  add_timestamp_to_vis: true
  transform_to_01: true
  vis_image_type: "pdf"

  model_save_dir: nn_models

  use_node_gene_data: 1
  use_edge_gene_data: 1
  use_edge_weights_data: 0
  use_recurrent_edge_gene_data: 1
  use_recurrent_edge_weights_data: 0


multiple_choice_args:

  reduction_type:
    - option: pca
      selected: 1

    - option: svd
      selected: 0

    - option: mds
      selected: 0

    - option: nn
      selected: 0

    - option: snn
      selected: 0

  run_type:
    - option: evoviz_examples_neat_high_speciation_1epoch
      selected: 0
    - option: evoviz_examples_neat_high_speciation_10epochs
      selected: 0
    - option: evoviz_examples_neat_low_speciation_10epochs
      selected: 0
    - option: evoviz_examples_neat_low_speciation_1epoch
      selected: 0
    - option: evoviz_examples_no_repop_10epochs
      selected: 0
    - option: evoviz_examples_no_repop_1epoch
      selected: 0
    - option: evoviz_examples_repop_10epochs
      selected: 1
    - option: evoviz_examples_repop_1epoch
      selected: 0

  visualization_type:
    - option: "2D"
      selected: 1

    - option: "3D"
      selected: 0

    - option: "3D-frames"
      selected: 0

    - option: "microscope"
      selected: 0

  interpolation_type:
    - option: cubic
      selected: 1

    - option: nn
      selected: 0
