
args:
  data_source_path: PUT_THE_PATH_TO_DATA_HERE
  node_size: 4
  arrow_size: 2
  line_width: 0.2
  3D_node_alpha: 1.0
  3D_line_alpha: 0.1
  subgraph_node_size: 100
  subgraph_width: 0.3
  subgraph_height: 0.3
  subgraph_x_spacing: 1
  subgraph_y_spacing: 1
  epochs: 2000
  verbose: true
  add_timestamp_to_vis: true
  transform_to_01: true
  vis_image_type: "pdf"
  use_node_gene_data: true
  use_edge_gene_data: true
  use_edge_weights_data: true
  use_recurrent_edge_gene_data: true
  use_recurrent_edge_weights_data: true


multiple_choice_args:

  reduction_type:
    - option: pca
      selected: true

    - option: svd
      selected: false

    - option: mds
      selected: false

    - option: nn
      selected: false

    - option: snn
      selected: false

  run_type:
    - option: evoviz_examples_neat_low_speciation_10epochs
      selected: false
    - option: evoviz_examples_neat_low_speciation_1epoch
      selected: false
    - option: evoviz_examples_no_repop_10epochs
      selected: false
    - option: evoviz_examples_no_repop_1epoch
      selected: false
    - option: evoviz_examples_repop_10epochs
      selected: false
    - option: evoviz_examples_repop_1epoch
      selected: false
    - option: no-repopulation
      selected: true

  visualization_type:
    - option: "2D"
      selected: true

    - option: "3D"
      selected: false

    - option: "microscope"
      selected: false
