
args:
  data_source_path: PUT_THE_PATH_TO_DATA_HERE
  node_size: 4
  arrow_size: 2
  line_width: 0.2
  3D_node_alpha: 1.0
  3D_line_alpha: 0.1
  subgraph_node_size: 100
  subgraph_width: 0.3
  subgraph_height: 0.3
  subgraph_x_spacing: 1
  subgraph_y_spacing: 1
  epochs: 2000
  verbose: true
  add_timestamp_to_vis: true
  transform_to_01: true
  vis_image_type: "pdf"
  use_node_gene_data: true
  use_edge_gene_data: true
  use_edge_weights_data: true
  use_recurrent_edge_gene_data: true
  use_recurrent_edge_weights_data: true


multiple_choice_args:

  reduction_type:
    - option: pca
      selected: 1

    - option: svd
      selected: 0

    - option: mds
      selected: 0

    - option: nn
      selected: 0

    - option: snn
      selected: 0

  run_type:
    - option: example_option
      selected: 1

  visualization_type:
    - option: "2D"
      selected: 1

    - option: "3D"
      selected: 0

    - option: "microscope"
      selected: 0
